<?php

namespace AppBundle\Repository;

/**
 * AAAARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AAAARepository extends \Doctrine\ORM\EntityRepository
{
}
